version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 16

  - package-ecosystem: "cargo"
    directory: "/nican"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/rs-can"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/socketcan"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/zlgcan"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
